### ISSUE TITLE
x64-bit version?

### ISSUE THREAD

**Issue by ImSpecial** [MyTDT-Mysoft/DarkTheme-Npp-Plugin#1]
Seems my notepad++ can't load this .dll because it's 32-bit, do you have plans on supporting 64-bit?

**Comment by MyTDT-Mysoft** [comment]
yes, i need to port one component of it to 64bit to be able to compile it then i will do the 64bit release

**Comment by ImSpecial** [comment]
Right on! I'll be looking forward to its release then.

BTW, are there any screenshots?
